version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 21 e npm...
      - curl -fsSL https://rpm.nodesource.com/setup_21.x | sudo bash -
      - sudo yum install -y nodejs
      - npm install --loglevel=error
  build:
    commands:
      - echo Running Migrate db
      - npx sequelize db:migrate
